[package]
name = "padauk_macros"
version = "0.1.0"
edition = "2024"

[lib]
name = "padauk_macros"
proc-macro = true
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = { version = "2.0.114", features = ["full"] }
